# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    site_key: "%recaptcha_key%"

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    csv_parser_services:
        class: AppBundle\Services\CSVParserServices
    mot_builder:
        class: AppBundle\Services\MotBuilderService
        arguments: ["@doctrine"]
    definition_builder:
        class: AppBundle\Services\DefinitionBuilderService
        arguments: ["@doctrine"]
    exemple_builder:
        class: AppBundle\Services\ExempleBuilderService
        arguments: ["@doctrine"]
    recaptcha_services:
        class: AppBundle\Services\reCaptchaServices
        arguments: ["%site_key%", "%recaptcha_site_key%"]