# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value
    site_key: "%recaptcha_key%"

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
    csv_parser_services:
        class: AppBundle\Services\CSVParserServices
    mot_builder:
        class: AppBundle\Services\MotBuilderService
        arguments: ["@doctrine"]
    definition_builder:
        class: AppBundle\Services\DefinitionBuilderService
        arguments: ["@doctrine"]
    exemple_builder:
        class: AppBundle\Services\ExempleBuilderService
        arguments: ["@doctrine"]
    recaptcha_services:
        class: AppBundle\Services\reCaptchaServices
        arguments: ["%site_key%", "%recaptcha_site_key%"]
    mailer_services:
        class: AppBundle\Services\MailerServices
        arguments: ["@mailer", "%admin_mail%", "@templating"]
    entity_listener_resolver:
        class: AppBundle\Doctrine\EntityListenerResolver
        arguments: [ "@service_container" ]
    mot_backup_service:
        class: AppBundle\Services\MotBackUpServices
        arguments: ["@doctrine"]
    definition_backup_service:
        class: AppBundle\Services\DefinitionBackUpServices
        arguments: ["@doctrine"]
    exemple_backup_service:
        class: AppBundle\Services\ExempleBackUpServices
        arguments: ["@doctrine"]
    mot_listener:
        class: AppBundle\Entity\Listener\MotListener
        arguments: ["@mailer_services", "@mot_backup_service"]
        tags:
            -  { name: doctrine.entity_listener }
    definition_listener:
        class: AppBundle\Entity\Listener\DefinitionListener
        arguments: ["@mailer_services", "@definition_backup_service"]
        tags:
            -  { name: doctrine.entity_listener }
    exemple_listener:
        class: AppBundle\Entity\Listener\ExempleListener
        arguments: ["@mailer_services", "@exemple_backup_service"]
        tags:
            -  { name: doctrine.entity_listener }
    mot_jour_manager:
        class: AppBundle\Services\MotJourManagerServices
        arguments: ["@doctrine"]