<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BackUpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BackUpRepository extends EntityRepository
{
    public function findMotByMotId($id){
        $query = $this->createQueryBuilder('v')
                        ->where('v.motId = :motId')
                        ->setParameter('motId', $id)
                        ->getQuery();
        
        return $query->getResult();
    }
}
