<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * MotDuJourRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MotDuJourRepository extends EntityRepository
{
    public function findLast(){
        return $this->createQueryBuilder('u')
            ->orderBy('u.id', 'DESC')
            ->setMaxResults(1)
            ->getQuery()
            ->getSingleResult();
    }
}
