<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;
use AppBundle\Entity\Vote;

/**
 * VoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VoteRepository extends EntityRepository
{
    public function hasAlreadyVoted($motId, $ip)
    {
        $query = $this->createQueryBuilder('v')
                        ->where('v.mot = :motId')
                        ->setParameter('motId', $motId)
                        ->andWhere('v.ip = :ip')
                        ->setParameter('ip', $ip)
                        ->getQuery();
        
        return $query->getResult();
    }
}
